apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: test-ingres.master1.loc
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-test
              port:
                number: 8080

